language: node_js
node_js:
- '11'
cache:
  directories:
  - "~/.npm"
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
jobs:
  include:
  - stage: release
    if: branch = master AND NOT type = pull_request
    deploy:
      provider: script
      script:
      - npm run deploy-docs
      - npx semantic-release --allow-same-version
