language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: true
node_js:
- '11'
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  run travis-deploy-once "npm run deploy-docs"; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  global:
  - secure: OxxdVo+4DgB1BI5BsWsQiSllqVxgfEYWAOP669/RxrXT7Ny1plkppy2cqkePQ6RzqYDQ8XLPQOidhiB+D/4HS4ZNChon1kzR+RTUMpNZ0wgDgmwkUQF+JB3eNF3BBlsn9/JUBDqDegJ+LC2cr3oQDjEnwnk/ut0H9dWRYxH4jeYAi6XzbsG8X9m3Mx23riits/3uWMh65E0Uzq4ByZOBzNDsSxJz+62isdD9fJqkPSxaMw6zieL/Ev4ylIfjSqLFphq16UIEiIKT634nPWoIwYvA3cRGoWcNstoRJeY2oNDCvZGVFY7vZ2mWAawlRDFGPEpJlL7Cw0G34XZ/RcP+2i2/sFeseSM51nrhrVgqjl3gTdpWOGSe9LNDnwa9t1pbrFgfkEi/0yJy+Cseg6LnAKcCb5s+07neckFjPGZygVHIWd2MxLeVGU7W3ZFsT3FgjhYDkK3G+dKLVWnA5J9dbCDKDMi9lVMS8xopMNxxVLSsm2CCV1w/joOIadFul1JSiRp9V4Nou+AFm1tOP4u4o9goD7VSMGWIXrx1Y36knN55Z6Safu2O7GeiBVZovBFrLF+0RFnx+wCa06kFSx82DpZ9tEFzIwdMrocpg0J2S1XG7eTXdjeJPzwCxNgVqALTEzwd+lnB1OziEdUWzt9UiX4zbcncFTrANcV2Nmx8JZw=
  - secure: EaLomeBpsDijq4a1WqG0hQjaI8QZVBjHzpV1UBoOUsfKQTIulVPoZlSVBhbK6gXLLOOlok8bhKlREeHf4Zb3fFIPgfgFvBgUwY/056/uwN2xcnwXXFOCbs1CPol+/+Em81MR/fqdCoh6KEuUCyP/QPXuOpBKVFDPid1oSuW89p2OeL4ekA4Ptqm8G0F8hTodb6FzSciKCuP9wv0J+RQjxLGdZ+oMJIlhxWjCG+3JPoyzkfHbJWMvgir5z9yUTgFu6v41SF8Cd4x+TAE5hHi5DiBY9Xk57EQtrT8+f3DabvUO8PBGLRNpSHQqmmpw2iPV++UWtfsn+gdhk+HJCAwVYMwJcZptMTf35+U2nbQpvRLwuwLhwlGZ6W/kAEVyDHsOVPWn+oSRrIsp6rBJaxNo+idm9I7cg65FguDWv8bNVT11thuOe6HcT6bWKD8t+3kSmBvAwm1tDE6wO04my6K/mUD+nVgF3Hbdyayx35T1soqo0cjhnAspptZKBuI4kGgrgHLNCmaUZAohdsu38dFIUecjT7U69Pwzc3Ydo6aq55XD3HbkuIOHohIY/Pi9TLieMkJeuCTMDod/w94ybYRrveHsgLpa+QCxkBLE2xxzP/GhQOzkvbQ3kRehqRpECX66wOa+ssQHmkKimPyuunmjztr7RUTjn0hy0WPrOfVYwVI=
