language: node_js
cache:
  directories:
  - "~/.npm"
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
  - stage: release
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx deploy-docs
      - npx semantic-release
