language: node_js
node_js:
- '11'
cache:
  directories:
  - "~/.npm"
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy-docs; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx semantic-release --allow-same-version; fi
