language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: true
node_js:
- '11'
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  run travis-deploy-once "npm run deploy-docs"; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  secure: mPSrV0k1tDIZjoHsYVNdIj6phaVqZgVaeddiq4FTnxKxeXMifBajVxe3KSjEeuXBClLjpBlnKicJJhHiKFYosabj+S2HOlJjYnlTTzYIOSd39bEbaaWUj8+qZa/bVNLJl+i7hTK1OnpnPbJsVkBGFJfNe6HfSaD05unax+czc1IquzXm0NQuY99pgzYRjratfHrxZIBjVJSgvV6w/dVOn+JyJfvrmpi2HxcMCPlHYbKh7k/F7bstTSaqqMonh8j0+Iih2seaefhcUsS+/NT8hhiutxAakS/Mo3Lguf8/Lkhg2e9EokygsymV2E0GvJadFCoEtMER7rYnG0KYRUicQNVxHWOYq4yg1TJa64N1CdVVjZ5Cjzm/bjbjMmghi/gKK8+mqYfmrQqKm31lH6FCSrlL/+CQYzjjCQ+7eiK88bmn0GKePtpRJJhBw1vPPRse4wP4d7Y/pi6he4l/JKXHgolWbbHhnIXCOfVn+DnvHqWf7nZvspRIgnvCHRiwyXyCD8H1i16xnCxZdmh41ohD9r8VoAWQ+7wueFfmMZk6ZqwAOVKYB8pRoJxkqXR6bAP87TSiW+UICRhSePu5/h8LSv7eC7O1fDHfEIGNAmRccnMhPMq8JhjK1newuIxgy5TkNwX/x95MDvQWWvItHj0pLJsZuxEbHq10vwOEw7hyDGU=
